# Generated by Django 5.0.4 on 2024-12-30 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dthamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Postpaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postpaidid', models.CharField(default='', max_length=50)),
                ('postpaidamount', models.IntegerField(default='')),
                ('month', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prepaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepaidamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datavalidity', models.IntegerField(default='')),
                ('datavalue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifiamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity', models.IntegerField(default='')),
                ('speed', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Upi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upiid', models.CharField(max_length=50)),
                ('upipassword', models.CharField(max_length=50)),
                ('expirydate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.IntegerField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cvv', models.IntegerField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cardnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentz.userdata')),
            ],
        ),
    ]
