# Generated by Django 5.1.5 on 2025-01-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='expirydate',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
